model:
  name: b-verma/BERTopic_ML-ArXiv-Abstracts
  source: https://huggingface.co/b-verma/BERTopic_ML-ArXiv-Abstracts
  version: 62f9c0c381c8771a76b99c753c883ca4ffd94ec6
  lang: EN
  cache_size: 3

annotation:
  name: test
  version: 1

log_level: DEBUG